import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import '@testing-library/jest-dom/vitest';
import { WelcomePage } from './WelcomePage';
import { BrowserRouter } from 'react-router-dom';

// Mock Clerk
const mockOpenSignIn = vi.fn();
vi.mock('@clerk/clerk-react', () => ({
  useClerk: () => ({
    openSignIn: mockOpenSignIn,
  }),
}));

// Mock react-i18next with actual translations
vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, defaultValueOrOptions?: string | Record<string, unknown>) => {
      // Map of translation keys to values
      const translations: Record<string, string> = {
        'welcome.hero.newBadge': '✨ Introducing Liquid Glass Design',
        'welcome.hero.titlePart1': 'Transcribe & Summarize',
        'welcome.hero.titlePart2': 'In Seconds',
        'welcome.hero.description':
          'Transform your meetings, lectures, and interviews into actionable insights. Start with 60 free minutes, upgrade for unlimited access.',
        'welcome.hero.cta.primary': 'Start Free Trial',
        'welcome.hero.cta.secondary': 'View Pricing',
        'welcome.hero.cta.appPreview': '[App Preview Visualization]',
        'welcome.hero.noCreditCard': 'No credit card required',
        'welcome.features.title': 'Power Tools for Audio',
        'welcome.features.subtitle': 'Everything you need to master your recordings.',
        'welcome.features.cards.transcription.title': 'Crystal Clear Transcription',
        'welcome.features.cards.transcription.description':
          'Upload files or record directly. Accurate transcription for reliable records using advanced on-device processing.',
        'welcome.features.cards.summaries.title': 'Instant AI Summaries',
        'welcome.features.cards.summaries.description':
          'Get key points, action items, and structured summaries automatically generated by top-tier AI models.',
        'welcome.features.cards.security.title': 'Private & Secure',
        'welcome.features.cards.security.description':
          'Your data stays yours. Client-side processing ensures maximum privacy. No audio leaves your device without permission.',
        'welcome.team.title': 'Our Team',
        'welcome.team.subtitle': 'Meet the Minds Behind Trammarise',
        'welcome.footer.tagline': 'AI-powered audio transcription and summarization',
        'welcome.footer.links.docs': 'Documentation',
        'welcome.footer.links.pricing': 'Pricing',
        'welcome.footer.links.privacy': 'Privacy',
        'welcome.footer.links.terms': 'Terms',
        'welcome.footer.links.contact': 'Contact',
      };

      // If defaultValueOrOptions is a string, return it as the default value
      if (typeof defaultValueOrOptions === 'string') {
        return defaultValueOrOptions;
      }

      // Handle interpolation for footer copyright
      if (key === 'welcome.footer.copyright') {
        return `© ${defaultValueOrOptions?.year || 2024} Trammarise. All rights reserved.`;
      }

      // Return translation or key as fallback
      return translations[key] || key;
    },
  }),
}));

// Mock Lucide icons to avoid ESM issues in tests if any
vi.mock('lucide-react', () => ({
  ArrowRight: () => <div data-testid="arrow-right" />,
  Mic: () => <div data-testid="mic" />,
  Zap: () => <div data-testid="zap" />,
  Shield: () => <div data-testid="shield" />,
  Check: () => <div data-testid="check-icon" />,
  Key: () => <div data-testid="key-icon" />,
  Github: () => <div data-testid="github" />,
  Linkedin: () => <div data-testid="linkedin" />,
  Twitter: () => <div data-testid="twitter" />,
}));

describe('WelcomePage', () => {
  it('renders the hero section correctly', () => {
    render(
      <BrowserRouter>
        <WelcomePage />
      </BrowserRouter>
    );

    expect(screen.getByText(/Transcribe & Summarize/i)).toBeInTheDocument();
    expect(screen.getByText(/In Seconds/i)).toBeInTheDocument();
    expect(screen.getByText(/Transform your meetings/i)).toBeInTheDocument();
  });

  it('renders the features section', () => {
    render(
      <BrowserRouter>
        <WelcomePage />
      </BrowserRouter>
    );

    expect(screen.getByText('Crystal Clear Transcription')).toBeInTheDocument();
    expect(screen.getByText('Instant AI Summaries')).toBeInTheDocument();
    expect(screen.getByText('Private & Secure')).toBeInTheDocument();
  });

  it('renders the team section', () => {
    render(
      <BrowserRouter>
        <WelcomePage />
      </BrowserRouter>
    );

    expect(screen.getByText('Our Team')).toBeInTheDocument();
    expect(screen.getByText('Meet the Minds Behind Trammarise')).toBeInTheDocument();
    expect(screen.getByText('Alex Chen')).toBeInTheDocument();
    expect(screen.getByText('Sarah Johnson')).toBeInTheDocument();
    expect(screen.getByText('Michael Brown')).toBeInTheDocument();
    expect(screen.getByText('Emily Davis')).toBeInTheDocument();
  });

  it('calls openSignIn when "Get Started" is clicked', () => {
    render(
      <BrowserRouter>
        <WelcomePage />
      </BrowserRouter>
    );

    const buttons = screen.getAllByText('Get Started Free');
    fireEvent.click(buttons[0]); // Click the hero button

    expect(mockOpenSignIn).toHaveBeenCalledWith({
      afterSignInUrl: '/',
      afterSignUpUrl: '/',
    });
  });

  it('renders navigation links in footer', () => {
    render(
      <BrowserRouter>
        <WelcomePage />
      </BrowserRouter>
    );

    expect(screen.getByText('Privacy')).toBeInTheDocument();
    expect(screen.getByText('Terms')).toBeInTheDocument();
    expect(screen.getByText('Contact')).toBeInTheDocument();
  });
});
